CREATE TABLE purchase(
  ID NUMBER GENERATED ALWAYS as IDENTITY(START with 1 INCREMENT by 1),
  username VARCHAR2(30) NOT NULL,
  instrument_id NUMBER NOT NULL,
  shop_id NUMBER,
  date_of_entry DATE DEFAULT SYSDATE
)TABLESPACE users;
